apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-next-13
  labels:
    app: app-next-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-next-13
  template:
    metadata:
      labels:
        app: app-next-13
    spec:
      containers:
      - image:  gcr.io/sitios-381213/app-next-13:latest
        name: app-next-13
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-next-13
  labels:
    run: app-next-13
spec:
  type: LoadBalancer
  selector:
    app: app-next-13
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000